#pragma once
struct MASTERY_ITEM_EXT_OPTION_SET
{
	int ItemType;
	int ItemIndex;
	BYTE ExtOption[6];
	int Rate;
};

struct MASTERY_OPTION
{
	int index;
	int level[10];
};

enum eMasteryOption
{
	//SETS
	MASTERY_OPTION_DAMAGE_AGAINST_DW = 6,
	MASTERY_OPTION_DAMAGE_AGAINST_DK,
	MASTERY_OPTION_DAMAGE_AGAINST_FE,
	MASTERY_OPTION_DAMAGE_AGAINST_MG,
	MASTERY_OPTION_DAMAGE_AGAINST_DL,
	MASTERY_OPTION_DAMAGE_AGAINST_SU,
	MASTERY_OPTION_DAMAGE_AGAINST_RF,
	MASTERY_OPTION_DAMAGE_AGAINST_GL,
	MASTERY_OPTION_INCREASE_BOSS_DAMAGE,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_INCREASE,
	//SHIELD
	MASTERY_OPTION_PVP_DAMAGE_REDUCTION = 20,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_REDUCTION,
	MASTERY_OPTION_DOUBLE_DAMAGE_PROTECTION,
	MASTERY_OPTION_TRIPLE_DAMAGE_PROTECTION,
	MASTERY_OPTION_TRUE_DAMAGE_PROTECTION,
	MASTERY_OPTION_ULTRAHIT_PROTECTION,
	//SETS BLUE EYE
	MASTERY_OPTION_DAMAGE_AGAINST_DW2 = 46,
	MASTERY_OPTION_DAMAGE_AGAINST_DK2,
	MASTERY_OPTION_DAMAGE_AGAINST_FE2,
	MASTERY_OPTION_DAMAGE_AGAINST_MG2,
	MASTERY_OPTION_DAMAGE_AGAINST_DL2,
	MASTERY_OPTION_DAMAGE_AGAINST_SU2,
	MASTERY_OPTION_DAMAGE_AGAINST_RF2,
	MASTERY_OPTION_DAMAGE_AGAINST_GL2,
	MASTERY_OPTION_INCREASE_BOSS_DAMAGE2,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_INCREASE2,
	//SHIELD BLUE EYE
	MASTERY_OPTION_PVP_DAMAGE_REDUCTION_2 = 60,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_REDUCTION_2,
	MASTERY_OPTION_DOUBLE_DAMAGE_PROTECTION_2,
	MASTERY_OPTION_TRIPLE_DAMAGE_PROTECTION_2,
	MASTERY_OPTION_TRUE_DAMAGE_PROTECTION_2,
	MASTERY_OPTION_ULTRAHIT_PROTECTION_2,
};

enum eMasteryOptionWeapon
{
	MASTERY_OPTION_BOSS_DECREASE_DELAY = 8,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_INCREASE_WEAPON,
	MASTERY_OPTION_BOSS_DAMAGE_INCREASE,
	MASTERY_OPTION_PVP_DAMAGE_INCREASE,
	MASTERY_OPTION_DOUBLE_DAMAGE_RATE,
	MASTERY_OPTION_TRIPLE_DAMAGE_RATE,
	MASTERY_OPTION_TRUE_DAMAGE_RATE,
	MASTERY_OPTION_30P_HP_ULTRAHIT,
	MASTERY_OPTION_BOSS_DECREASE_DELAY_2,
	MASTERY_OPTION_ELEMENTAL_DAMAGE_INCREASE_WEAPON_2,
	MASTERY_OPTION_BOSS_DAMAGE_INCREASE_2,
	MASTERY_OPTION_PVP_DAMAGE_INCREASE_2,
	MASTERY_OPTION_DOUBLE_DAMAGE_RATE_2,
	MASTERY_OPTION_TRIPLE_DAMAGE_RATE_2,
	MASTERY_OPTION_TRUE_DAMAGE_RATE_2,
	MASTERY_OPTION_30P_HP_ULTRAHIT_2
};

enum eMasteryOptionPendant
{
	MASTERY_OPTION_PENDANT_PVP_DMG = 30,
	MASTERY_OPTION_PENDANT_TRIPLE_DMG,
	MASTERY_OPTION_PENDANT_TRUE_DMG,
	MASTERY_OPTION_PENDANT_DOUBLE_DMG,
	MASTERY_OPTION_PENDANT_BOSS_DMG,
	MASTERY_OPTION_PENDANT_BOSS_DECREASE_DELAY,
	MASTERY_OPTION_PENDANT_ELEMENTAL_DAMAGE_INCREASE
};

enum eMasteryBonusPendant
{
	MASTERY_BONUS_PENDANT_CURE_HARM = 20,
	MASTERY_BONUS_PENDANT_STERN,
	MASTERY_BONUS_PENDANT_BLEEDING,
	MASTERY_BONUS_PENDANT_SHIELD_SKILL_IGNORE,
	MASTERY_BONUS_PENDANT_ULTRAHIT_50
};

enum eMasteryOptionRing
{
	MASTERY_OPTION_RING_BACKSPRING_PROTECTION = 30,
	MASTERY_OPTION_RING_DROP_BOSS_INC,
	MASTERY_OPTION_RING_MAX_HP_INC,
	MASTERY_OPTION_RING_BLOCK_CHANCE_INC,
	MASTERY_OPTION_RING_BOSS_SKILL_PROTECTION,
	MASTERY_OPTION_RING_ELEMENTAL_DMG_REDUCE,
	MASTERY_OPTION_RING_PVP_DAMAGE_REDUCE,
	MASTERY_OPTION_RING_BOSS_DAMAGE_REDUCE,
	MASTERY_OPTION_RING_TRIPLE_DMG_PROTECTION,
	MASTERY_OPTION_RING_TRUE_DMG_PROTECTION
};

enum eMasteryBonusRing
{
	MASTERY_BONUS_RING_STERN_RESIST = 20,
	MASTERY_BONUS_RING_BLEEDING_RESIST,
	MASTERY_BONUS_RING_CURE_HARM_RESIST,
	MASTERY_BONUS_RING_CURE_IMPROVE,
	MASTERY_BONUS_RING_FULL_REFLECT_INC,
	MASTERY_BONUS_RING_MASTERY_REVERT
};

enum eMasteryBonus
{
	//Sets
	MASTERY_BONUS_TRIPLE_DAMAGE_RATE = 1,
	MASTERY_BONUS_FINAL_DAMAGE,
	MASTERY_BONUS_ULTRAHIT_50,
	MASTERY_BONUS_DOUBLE_DAMAGE_BOSS,
	//Shield
	MASTERY_BONUS_HP_DAMAGE_PROTECTION = 7,
	MASTERY_BONUS_REFLECT_INCREASE,
	MASTERY_BONUS_BOSS_POWER_PROTECTION,
	//Set Blue Eye
	MASTERY_BONUS_TRIPLE_DAMAGE_RATE2 = 10,
	MASTERY_BONUS_FINAL_DAMAGE2,
	MASTERY_BONUS_ULTRAHIT_502,
	MASTERY_BONUS_DOUBLE_DAMAGE_BOSS2,
	//Shield Blue Eye
	MASTERY_BONUS_HP_DAMAGE_PROTECTION_2 = 14,
	MASTERY_BONUS_REFLECT_INCREASE_2,
	MASTERY_BONUS_BOSS_POWER_PROTECTION_2,
};

enum eMasteryWeaponBonus
{
	MASTERY_BONUS_ULTRAHIT_50_WEAPON = 1,
	MASTERY_BONUS_100P_EXCELLENT,
	MASTERY_BONUS_REFLECT_DECREASE,
	MASTERY_BONUS_CURE_HARM,
	MASTERY_BONUS_STERN_RATE,
	MASTERY_BONUS_BLEEDING,
	MASTERY_BONUS_DOUBLE_DAMAGE_BOSS_WEAPON,
	MASTERY_BONUS_ULTRAHIT_50_WEAPON_2,
	MASTERY_BONUS_FREEZING_DAMAGE,
	MASTERY_BONUS_REFLECT_DECREASE_2,
	MASTERY_BONUS_CURE_HARM_2,
	MASTERY_BONUS_STERN_RATE_2,
	MASTERY_BONUS_BLEEDING_2,
	MASTERY_BONUS_DOUBLE_DAMAGE_BOSS_WEAPON_2,
};

class MasteryItemExtOptionSet
{
public:
	MasteryItemExtOptionSet();
	~MasteryItemExtOptionSet();
	void Load(char* path);
	BOOL  RandMasteryItemExtOption(int iType, int iIndex, BYTE *ExtOp);
	BOOL IsMasteryItem(int Index);
	BOOL IsMasterySet(int Index);
	BOOL IsMasteryWeapon(int Index);
	BOOL IsMasteryShield(int Index);
	BOOL IsMasteryRing(int Index);
	BOOL IsMasteryPendant(int Index);
	void CalcMasteryOption(LPOBJ lpObj, CItem * item);
	void CalcMasteryWeaponOption(LPOBJ lpObj, CItem* lpItem);
	void CalcMasteryPendantOption(LPOBJ lpObj, CItem* lpItem);
	void CalcMasteryRingOption(LPOBJ lpObj, CItem* lpItem);
private:
	MASTERY_ITEM_EXT_OPTION_SET m_MasteryItemExtOptionSet[100];
};
extern MasteryItemExtOptionSet gMasteryItemExtOptionSet;

