#pragma once
#include "User.h"

struct WING4THOPTION
{
	int index;
	int level[10];
};

struct WING4THELEMENT
{
	int index;
	int level[16];
};

enum eWing4thOption
{
	WING4TH_OPTION_REDUCAO_DANO_FINAL = 0,
	WING4TH_OPTION_HP_RECOVERY = 1,
	WING4TH_OPTION_REFLECT = 2,
	WING4TH_OPTION_IGNORE_DEFENSE = 3,
	WING4TH_OPTION_REDUCAO_DELAY_BOSS = 4,
	WING4TH_OPTION_EXCELLENT_DAMAGE_RATE = 5,
	WING4TH_OPTION_DOUBLE_DAMAGE_RATE = 6,
	WING4TH_OPTION_ADITIONAL_STRENGTH = 7,
	WING4TH_OPTION_ADITIONAL_VITALITY = 8,
	WING4TH_OPTION_ADITIONAL_ENERGY = 9,
	WING4TH_OPTION_ADITIONAL_AGILITY = 10,
	WING4TH_OPTION_ADICIONAL_DANO_FINAL = 11,
	WING4TH_OPTION_ADICIONAL_DANO_BOSS = 12,
	WING4TH_OPTION_RESISTENCIA_BOSS = 13,
	WING4TH_OPTION_BOSS_DROP_INCREASE = 14
};

enum eWing4thElemental
{
	WING4TH_ELEMENTAL_DANO_ELEMENTAL_PVP = 0,
	WING4TH_ELEMENTAL_CHANCE_PUNISH = 1,
	WING4TH_ELEMENTAL_RESISTENCIA_RADIANCE = 2,
	WING4TH_ELEMENTAL_DANO_ELEMENTAL_PVP_ELITE = 3,
	WING4TH_ELEMENTAL_DEFESA_ELEMENTAL_PVP = 4,
	WING4TH_ELEMENTAL_DANO_ELEMENTAL_BOSS = 5,
	WING4TH_ELEMENTAL_DEFESA_ELEMENTAL_BOSS = 6,
	WING4TH_ELEMENTAL_DANO_CONTRA_FOGO = 7,
	WING4TH_ELEMENTAL_DANO_CONTRA_AGUA = 8,
	WING4TH_ELEMENTAL_DANO_CONTRA_TERRA = 9,
	WING4TH_ELEMENTAL_DANO_CONTRA_VENTO = 10,
	WING4TH_ELEMENTAL_DANO_CONTRA_ESCURIDAO = 11,
	WING4TH_ELEMENTAL_DANO_ELEMENTAL_BOSS_ELITE = 12,
	WING4TH_ELEMENTAL_DEFESA_ELEMENTAL_BOSS_ELITE = 13
};

class CWings4thOption
{
public:
	CWings4thOption();
	virtual ~CWings4thOption();
	void Load();
	void SetInfo(WING4THOPTION info);
	void SetElementalInfo(WING4THELEMENT info);
	void Calc4thWingOption(LPOBJ lpObj, bool flag);
	WING4THOPTION Wing4thOption[15];
	WING4THELEMENT Wing4thElemental[14];
	int Wing4thElementalBasic[16];
};

extern CWings4thOption gWings4thOption;